### ISSUE TITLE
Need some help with large input.

### ISSUE THREAD

**Issue by vinayprolitus** [legendarykamal/ZkPod#2]
Hello guys, I had no other way to communicate with you guys so opening an issue here.
I am looking for a solution to generate ZKP for a large data. An array of json objects with length in 10k - 100k or even more.

Our use case is to fetch a high number of users based on various filters and generate proof for it.
I was looking into zk-POD but it's not maintained anymore and found your repo during the search.

I wrote a circuit in zokrates but it failed on large input.

**Comment by kamalbuilds** [comment]
Hi @vinayprolitus , this might be due to the **proof generation process being computationally intensive.**

One option to solve this might be to optimize your circuit to reduce the number of constraints and variables, which can help to reduce the computational requirements of proof generation.

**Comment by kamalbuilds** [comment]
Also, I have opened a discussions forum which might be the best place for these discussions . Thanks.
